#include "slim_hl.h"
#include <string.h>
#include <stdlib.h>
#include <unistd.h>

#define HL_RESET   "\x1b[0m"
#define HL_KEYWORD "\x1b[35m"
#define HL_TYPE    "\x1b[34m"
#define HL_STRING  "\x1b[32m"
#define HL_COMMENT "\x1b[90m"
#define HL_NUMBER  "\x1b[33m"
#define HL_PREPROC "\x1b[36m"
#define HL_ERROR   "\x1b[31m"

typedef struct {
    const char* word;
    int len;
} SlopKwEntry;

typedef struct {
    const char* single;
    const char* multi_start;
    const char* multi_end;
    const char* quotes;
    int has_preproc;
    SlopKwEntry* keywords;
    int kw_count;
    SlopKwEntry* types;
    int type_count;
} SlopLangProfile;

typedef enum {
    LANG_NONE = 0,
    LANG_C,
    LANG_CPP,
    LANG_RUST,
    LANG_GO,
    LANG_JAVASCRIPT,
    LANG_TYPESCRIPT,
    LANG_JAVA,
    LANG_PYTHON,
    LANG_SHELL,
    LANG_RUBY,
    LANG_PHP,
    LANG_LUA,
    LANG_PERL,
    LANG_SQL,
    LANG_SWIFT,
    LANG_KOTLIN,
    LANG_CSHARP,
    LANG_HTML,
    LANG_XML,
    LANG_CSS,
    LANG_JSON,
    LANG_YAML,
    LANG_TOML,
    LANG_INI,
    LANG_DOCKERFILE,
    LANG_MAKEFILE,
    LANG_LISP,
    LANG_HASKELL,
    LANG_ERLANG,
    LANG_MARKDOWN,
    LANG_ASSEMBLY,
    LANG_COUNT
} SlopLangId;

static SlopKwEntry c_keywords[] = {
    { "do", 2 },
    { "if", 2 },
    { "for", 3 },
    { "int", 3 },
    { "auto", 4 },
    { "bool", 4 },
    { "case", 4 },
    { "char", 4 },
    { "elif", 4 },
    { "else", 4 },
    { "enum", 4 },
    { "goto", 4 },
    { "line", 4 },
    { "long", 4 },
    { "NULL", 4 },
    { "true", 4 },
    { "void", 4 },
    { "_Bool", 5 },
    { "break", 5 },
    { "const", 5 },
    { "endif", 5 },
    { "error", 5 },
    { "false", 5 },
    { "float", 5 },
    { "ifdef", 5 },
    { "short", 5 },
    { "undef", 5 },
    { "union", 5 },
    { "while", 5 },
    { "atomic", 6 },
    { "define", 6 },
    { "double", 6 },
    { "extern", 6 },
    { "ifndef", 6 },
    { "inline", 6 },
    { "pragma", 6 },
    { "return", 6 },
    { "signed", 6 },
    { "sizeof", 6 },
    { "static", 6 },
    { "struct", 6 },
    { "switch", 6 },
    { "_Atomic", 7 },
    { "alignas", 7 },
    { "alignof", 7 },
    { "complex", 7 },
    { "default", 7 },
    { "defined", 7 },
    { "generic", 7 },
    { "include", 7 },
    { "typedef", 7 },
    { "warning", 7 },
    { "_Alignas", 8 },
    { "_Alignof", 8 },
    { "_Complex", 8 },
    { "_Generic", 8 },
    { "continue", 8 },
    { "noreturn", 8 },
    { "register", 8 },
    { "restrict", 8 },
    { "unsigned", 8 },
    { "volatile", 8 },
    { "_Noreturn", 9 },
    { "imaginary", 9 },
    { "_Imaginary", 10 },
    { "thread_local", 12 },
    { "_Thread_local", 13 },
    { "static_assert", 13 },
    { "_Static_assert", 14 },
};
static SlopKwEntry c_types[] = {
    { "int", 3 },
    { "bool", 4 },
    { "char", 4 },
    { "FILE", 4 },
    { "long", 4 },
    { "void", 4 },
    { "float", 5 },
    { "short", 5 },
    { "double", 6 },
    { "int8_t", 6 },
    { "signed", 6 },
    { "size_t", 6 },
    { "int16_t", 7 },
    { "int32_t", 7 },
    { "int64_t", 7 },
    { "ssize_t", 7 },
    { "uint8_t", 7 },
    { "uint16_t", 8 },
    { "uint32_t", 8 },
    { "uint64_t", 8 },
    { "SlopArena", 9 },
    { "SlopArray", 9 },
    { "SlopString", 10 },
    { "SlopTensor", 10 },
};

static SlopKwEntry cpp_keywords[] = {
    { "do", 2 },
    { "if", 2 },
    { "asm", 3 },
    { "for", 3 },
    { "int", 3 },
    { "new", 3 },
    { "try", 3 },
    { "auto", 4 },
    { "case", 4 },
    { "char", 4 },
    { "elif", 4 },
    { "else", 4 },
    { "enum", 4 },
    { "goto", 4 },
    { "line", 4 },
    { "long", 4 },
    { "NULL", 4 },
    { "this", 4 },
    { "true", 4 },
    { "void", 4 },
    { "break", 5 },
    { "catch", 5 },
    { "class", 5 },
    { "const", 5 },
    { "endif", 5 },
    { "error", 5 },
    { "false", 5 },
    { "float", 5 },
    { "ifdef", 5 },
    { "short", 5 },
    { "throw", 5 },
    { "undef", 5 },
    { "union", 5 },
    { "using", 5 },
    { "while", 5 },
    { "define", 6 },
    { "delete", 6 },
    { "double", 6 },
    { "export", 6 },
    { "extern", 6 },
    { "friend", 6 },
    { "ifndef", 6 },
    { "inline", 6 },
    { "pragma", 6 },
    { "public", 6 },
    { "return", 6 },
    { "signed", 6 },
    { "sizeof", 6 },
    { "static", 6 },
    { "struct", 6 },
    { "switch", 6 },
    { "typeid", 6 },
    { "concept", 7 },
    { "default", 7 },
    { "defined", 7 },
    { "include", 7 },
    { "mutable", 7 },
    { "nullptr", 7 },
    { "private", 7 },
    { "typedef", 7 },
    { "virtual", 7 },
    { "warning", 7 },
    { "wchar_t", 7 },
    { "co_await", 8 },
    { "co_yield", 8 },
    { "continue", 8 },
    { "decltype", 8 },
    { "explicit", 8 },
    { "noexcept", 8 },
    { "operator", 8 },
    { "register", 8 },
    { "requires", 8 },
    { "template", 8 },
    { "typename", 8 },
    { "unsigned", 8 },
    { "volatile", 8 },
    { "co_return", 9 },
    { "consteval", 9 },
    { "constexpr", 9 },
    { "constinit", 9 },
    { "namespace", 9 },
    { "protected", 9 },
    { "const_cast", 10 },
    { "static_cast", 11 },
    { "dynamic_cast", 12 },
    { "reinterpret_cast", 16 },
};
static SlopKwEntry cpp_types[] = {
    { "int", 3 },
    { "map", 3 },
    { "set", 3 },
    { "bool", 4 },
    { "char", 4 },
    { "FILE", 4 },
    { "long", 4 },
    { "void", 4 },
    { "float", 5 },
    { "short", 5 },
    { "double", 6 },
    { "int8_t", 6 },
    { "signed", 6 },
    { "size_t", 6 },
    { "string", 6 },
    { "vector", 6 },
    { "int16_t", 7 },
    { "int32_t", 7 },
    { "int64_t", 7 },
    { "ssize_t", 7 },
    { "uint8_t", 7 },
    { "wchar_t", 7 },
    { "uint16_t", 8 },
    { "uint32_t", 8 },
    { "uint64_t", 8 },
    { "unordered_map", 13 },
    { "unordered_set", 13 },
};

static SlopKwEntry rust_keywords[] = {
    { "as", 2 },
    { "fn", 2 },
    { "if", 2 },
    { "in", 2 },
    { "dyn", 3 },
    { "for", 3 },
    { "let", 3 },
    { "mod", 3 },
    { "mut", 3 },
    { "pub", 3 },
    { "ref", 3 },
    { "use", 3 },
    { "else", 4 },
    { "enum", 4 },
    { "impl", 4 },
    { "loop", 4 },
    { "move", 4 },
    { "self", 4 },
    { "Self", 4 },
    { "true", 4 },
    { "type", 4 },
    { "async", 5 },
    { "await", 5 },
    { "break", 5 },
    { "const", 5 },
    { "crate", 5 },
    { "false", 5 },
    { "match", 5 },
    { "super", 5 },
    { "trait", 5 },
    { "union", 5 },
    { "where", 5 },
    { "while", 5 },
    { "extern", 6 },
    { "return", 6 },
    { "static", 6 },
    { "struct", 6 },
    { "unsafe", 6 },
    { "continue", 8 },
    { "macro_rules", 11 },
};
static SlopKwEntry rust_types[] = {
    { "i8", 2 },
    { "Rc", 2 },
    { "u8", 2 },
    { "Arc", 3 },
    { "Box", 3 },
    { "f32", 3 },
    { "f64", 3 },
    { "i16", 3 },
    { "i32", 3 },
    { "i64", 3 },
    { "str", 3 },
    { "u16", 3 },
    { "u32", 3 },
    { "u64", 3 },
    { "Vec", 3 },
    { "bool", 4 },
    { "char", 4 },
    { "i128", 4 },
    { "u128", 4 },
    { "isize", 5 },
    { "usize", 5 },
    { "Option", 6 },
    { "Result", 6 },
    { "String", 6 },
};

static SlopKwEntry go_keywords[] = {
    { "go", 2 },
    { "if", 2 },
    { "for", 3 },
    { "map", 3 },
    { "var", 3 },
    { "case", 4 },
    { "chan", 4 },
    { "else", 4 },
    { "func", 4 },
    { "goto", 4 },
    { "type", 4 },
    { "break", 5 },
    { "const", 5 },
    { "defer", 5 },
    { "range", 5 },
    { "import", 6 },
    { "return", 6 },
    { "select", 6 },
    { "struct", 6 },
    { "switch", 6 },
    { "default", 7 },
    { "package", 7 },
    { "continue", 8 },
    { "interface", 9 },
    { "fallthrough", 11 },
};
static SlopKwEntry go_types[] = {
    { "int", 3 },
    { "bool", 4 },
    { "byte", 4 },
    { "int8", 4 },
    { "rune", 4 },
    { "uint", 4 },
    { "error", 5 },
    { "int16", 5 },
    { "int32", 5 },
    { "int64", 5 },
    { "uint8", 5 },
    { "string", 6 },
    { "uint16", 6 },
    { "uint32", 6 },
    { "uint64", 6 },
    { "float32", 7 },
    { "float64", 7 },
    { "uintptr", 7 },
    { "complex64", 9 },
    { "complex128", 10 },
};

static SlopKwEntry javascript_keywords[] = {
    { "do", 2 },
    { "if", 2 },
    { "in", 2 },
    { "for", 3 },
    { "let", 3 },
    { "NaN", 3 },
    { "new", 3 },
    { "try", 3 },
    { "var", 3 },
    { "case", 4 },
    { "else", 4 },
    { "null", 4 },
    { "this", 4 },
    { "true", 4 },
    { "void", 4 },
    { "with", 4 },
    { "async", 5 },
    { "await", 5 },
    { "break", 5 },
    { "catch", 5 },
    { "class", 5 },
    { "const", 5 },
    { "false", 5 },
    { "super", 5 },
    { "throw", 5 },
    { "while", 5 },
    { "yield", 5 },
    { "delete", 6 },
    { "export", 6 },
    { "import", 6 },
    { "return", 6 },
    { "switch", 6 },
    { "typeof", 6 },
    { "default", 7 },
    { "extends", 7 },
    { "finally", 7 },
    { "continue", 8 },
    { "debugger", 8 },
    { "function", 8 },
    { "Infinity", 8 },
    { "undefined", 9 },
    { "instanceof", 10 },
};

static SlopKwEntry typescript_keywords[] = {
    { "as", 2 },
    { "do", 2 },
    { "if", 2 },
    { "in", 2 },
    { "any", 3 },
    { "for", 3 },
    { "get", 3 },
    { "let", 3 },
    { "NaN", 3 },
    { "new", 3 },
    { "set", 3 },
    { "try", 3 },
    { "var", 3 },
    { "case", 4 },
    { "else", 4 },
    { "enum", 4 },
    { "null", 4 },
    { "this", 4 },
    { "true", 4 },
    { "type", 4 },
    { "void", 4 },
    { "with", 4 },
    { "async", 5 },
    { "await", 5 },
    { "break", 5 },
    { "catch", 5 },
    { "class", 5 },
    { "const", 5 },
    { "false", 5 },
    { "keyof", 5 },
    { "never", 5 },
    { "super", 5 },
    { "throw", 5 },
    { "while", 5 },
    { "yield", 5 },
    { "delete", 6 },
    { "export", 6 },
    { "import", 6 },
    { "module", 6 },
    { "public", 6 },
    { "return", 6 },
    { "static", 6 },
    { "switch", 6 },
    { "typeof", 6 },
    { "declare", 7 },
    { "default", 7 },
    { "extends", 7 },
    { "finally", 7 },
    { "private", 7 },
    { "unknown", 7 },
    { "abstract", 8 },
    { "continue", 8 },
    { "debugger", 8 },
    { "function", 8 },
    { "Infinity", 8 },
    { "readonly", 8 },
    { "interface", 9 },
    { "namespace", 9 },
    { "protected", 9 },
    { "satisfies", 9 },
    { "undefined", 9 },
    { "implements", 10 },
    { "instanceof", 10 },
};

static SlopKwEntry java_keywords[] = {
    { "do", 2 },
    { "if", 2 },
    { "for", 3 },
    { "int", 3 },
    { "new", 3 },
    { "try", 3 },
    { "byte", 4 },
    { "case", 4 },
    { "char", 4 },
    { "else", 4 },
    { "enum", 4 },
    { "goto", 4 },
    { "long", 4 },
    { "null", 4 },
    { "this", 4 },
    { "true", 4 },
    { "void", 4 },
    { "break", 5 },
    { "catch", 5 },
    { "class", 5 },
    { "const", 5 },
    { "false", 5 },
    { "final", 5 },
    { "float", 5 },
    { "short", 5 },
    { "super", 5 },
    { "throw", 5 },
    { "while", 5 },
    { "assert", 6 },
    { "double", 6 },
    { "import", 6 },
    { "native", 6 },
    { "public", 6 },
    { "return", 6 },
    { "static", 6 },
    { "switch", 6 },
    { "throws", 6 },
    { "boolean", 7 },
    { "default", 7 },
    { "extends", 7 },
    { "finally", 7 },
    { "package", 7 },
    { "private", 7 },
    { "abstract", 8 },
    { "continue", 8 },
    { "strictfp", 8 },
    { "volatile", 8 },
    { "interface", 9 },
    { "protected", 9 },
    { "transient", 9 },
    { "implements", 10 },
    { "instanceof", 10 },
    { "synchronized", 12 },
};

static SlopKwEntry python_keywords[] = {
    { "as", 2 },
    { "if", 2 },
    { "in", 2 },
    { "is", 2 },
    { "or", 2 },
    { "and", 3 },
    { "def", 3 },
    { "del", 3 },
    { "for", 3 },
    { "not", 3 },
    { "try", 3 },
    { "elif", 4 },
    { "else", 4 },
    { "from", 4 },
    { "None", 4 },
    { "pass", 4 },
    { "True", 4 },
    { "with", 4 },
    { "async", 5 },
    { "await", 5 },
    { "break", 5 },
    { "class", 5 },
    { "False", 5 },
    { "print", 5 },
    { "raise", 5 },
    { "while", 5 },
    { "yield", 5 },
    { "assert", 6 },
    { "except", 6 },
    { "global", 6 },
    { "import", 6 },
    { "lambda", 6 },
    { "return", 6 },
    { "finally", 7 },
    { "continue", 8 },
    { "nonlocal", 8 },
};

static SlopKwEntry shell_keywords[] = {
    { "do", 2 },
    { "fi", 2 },
    { "if", 2 },
    { "in", 2 },
    { "for", 3 },
    { "set", 3 },
    { "case", 4 },
    { "done", 4 },
    { "echo", 4 },
    { "elif", 4 },
    { "else", 4 },
    { "esac", 4 },
    { "eval", 4 },
    { "exec", 4 },
    { "exit", 4 },
    { "read", 4 },
    { "then", 4 },
    { "trap", 4 },
    { "break", 5 },
    { "local", 5 },
    { "shift", 5 },
    { "unset", 5 },
    { "until", 5 },
    { "while", 5 },
    { "export", 6 },
    { "printf", 6 },
    { "return", 6 },
    { "source", 6 },
    { "declare", 7 },
    { "typeset", 7 },
    { "continue", 8 },
    { "function", 8 },
    { "readonly", 8 },
};

static SlopKwEntry ruby_keywords[] = {
    { "do", 2 },
    { "if", 2 },
    { "in", 2 },
    { "or", 2 },
    { "and", 3 },
    { "def", 3 },
    { "end", 3 },
    { "for", 3 },
    { "nil", 3 },
    { "not", 3 },
    { "case", 4 },
    { "else", 4 },
    { "next", 4 },
    { "redo", 4 },
    { "self", 4 },
    { "then", 4 },
    { "true", 4 },
    { "when", 4 },
    { "alias", 5 },
    { "begin", 5 },
    { "break", 5 },
    { "class", 5 },
    { "elsif", 5 },
    { "false", 5 },
    { "retry", 5 },
    { "super", 5 },
    { "undef", 5 },
    { "until", 5 },
    { "while", 5 },
    { "yield", 5 },
    { "ensure", 6 },
    { "module", 6 },
    { "rescue", 6 },
    { "return", 6 },
    { "unless", 6 },
    { "defined?", 8 },
};

static SlopKwEntry php_keywords[] = {
    { "as", 2 },
    { "do", 2 },
    { "fn", 2 },
    { "if", 2 },
    { "or", 2 },
    { "and", 3 },
    { "die", 3 },
    { "for", 3 },
    { "new", 3 },
    { "try", 3 },
    { "use", 3 },
    { "var", 3 },
    { "xor", 3 },
    { "case", 4 },
    { "echo", 4 },
    { "else", 4 },
    { "eval", 4 },
    { "exit", 4 },
    { "goto", 4 },
    { "list", 4 },
    { "null", 4 },
    { "true", 4 },
    { "array", 5 },
    { "break", 5 },
    { "catch", 5 },
    { "class", 5 },
    { "clone", 5 },
    { "const", 5 },
    { "empty", 5 },
    { "endif", 5 },
    { "false", 5 },
    { "final", 5 },
    { "isset", 5 },
    { "match", 5 },
    { "print", 5 },
    { "throw", 5 },
    { "trait", 5 },
    { "unset", 5 },
    { "while", 5 },
    { "yield", 5 },
    { "elseif", 6 },
    { "endfor", 6 },
    { "global", 6 },
    { "public", 6 },
    { "return", 6 },
    { "static", 6 },
    { "switch", 6 },
    { "declare", 7 },
    { "default", 7 },
    { "extends", 7 },
    { "finally", 7 },
    { "foreach", 7 },
    { "include", 7 },
    { "private", 7 },
    { "require", 7 },
    { "abstract", 8 },
    { "callable", 8 },
    { "continue", 8 },
    { "endwhile", 8 },
    { "function", 8 },
    { "readonly", 8 },
    { "endswitch", 9 },
    { "insteadof", 9 },
    { "interface", 9 },
    { "namespace", 9 },
    { "protected", 9 },
    { "enddeclare", 10 },
    { "endforeach", 10 },
    { "implements", 10 },
    { "instanceof", 10 },
    { "include_once", 12 },
    { "require_once", 12 },
    { "__halt_compiler", 15 },
};

static SlopKwEntry lua_keywords[] = {
    { "do", 2 },
    { "if", 2 },
    { "in", 2 },
    { "or", 2 },
    { "and", 3 },
    { "end", 3 },
    { "for", 3 },
    { "nil", 3 },
    { "not", 3 },
    { "else", 4 },
    { "goto", 4 },
    { "then", 4 },
    { "true", 4 },
    { "break", 5 },
    { "false", 5 },
    { "local", 5 },
    { "until", 5 },
    { "while", 5 },
    { "elseif", 6 },
    { "repeat", 6 },
    { "return", 6 },
    { "function", 8 },
};

static SlopKwEntry perl_keywords[] = {
    { "q", 1 },
    { "y", 1 },
    { "do", 2 },
    { "fc", 2 },
    { "if", 2 },
    { "lc", 2 },
    { "my", 2 },
    { "no", 2 },
    { "or", 2 },
    { "qq", 2 },
    { "qr", 2 },
    { "qw", 2 },
    { "qx", 2 },
    { "uc", 2 },
    { "abs", 3 },
    { "and", 3 },
    { "chr", 3 },
    { "cmp", 3 },
    { "cos", 3 },
    { "die", 3 },
    { "eof", 3 },
    { "exp", 3 },
    { "for", 3 },
    { "hex", 3 },
    { "int", 3 },
    { "log", 3 },
    { "map", 3 },
    { "not", 3 },
    { "oct", 3 },
    { "ord", 3 },
    { "our", 3 },
    { "pop", 3 },
    { "pos", 3 },
    { "ref", 3 },
    { "say", 3 },
    { "sin", 3 },
    { "sub", 3 },
    { "tie", 3 },
    { "use", 3 },
    { "vec", 3 },
    { "xor", 3 },
    { "bind", 4 },
    { "chop", 4 },
    { "dump", 4 },
    { "each", 4 },
    { "else", 4 },
    { "eval", 4 },
    { "exec", 4 },
    { "exit", 4 },
    { "fork", 4 },
    { "goto", 4 },
    { "grep", 4 },
    { "join", 4 },
    { "keys", 4 },
    { "kill", 4 },
    { "last", 4 },
    { "link", 4 },
    { "next", 4 },
    { "open", 4 },
    { "pack", 4 },
    { "pipe", 4 },
    { "push", 4 },
    { "rand", 4 },
    { "read", 4 },
    { "recv", 4 },
    { "redo", 4 },
    { "seek", 4 },
    { "send", 4 },
    { "sort", 4 },
    { "sqrt", 4 },
    { "stat", 4 },
    { "tell", 4 },
    { "tied", 4 },
    { "time", 4 },
    { "wait", 4 },
    { "warn", 4 },
    { "atan2", 5 },
    { "bless", 5 },
    { "break", 5 },
    { "chdir", 5 },
    { "chmod", 5 },
    { "chomp", 5 },
    { "chown", 5 },
    { "close", 5 },
    { "crypt", 5 },
    { "elsif", 5 },
    { "fcntl", 5 },
    { "flock", 5 },
    { "index", 5 },
    { "ioctl", 5 },
    { "local", 5 },
    { "lstat", 5 },
    { "mkdir", 5 },
    { "print", 5 },
    { "reset", 5 },
    { "rmdir", 5 },
    { "semop", 5 },
    { "shift", 5 },
    { "sleep", 5 },
    { "split", 5 },
    { "srand", 5 },
    { "state", 5 },
    { "study", 5 },
    { "times", 5 },
    { "umask", 5 },
    { "undef", 5 },
    { "untie", 5 },
    { "until", 5 },
    { "utime", 5 },
    { "while", 5 },
    { "write", 5 },
    { "caller", 6 },
    { "chroot", 6 },
    { "delete", 6 },
    { "exists", 6 },
    { "fileno", 6 },
    { "format", 6 },
    { "length", 6 },
    { "listen", 6 },
    { "msgctl", 6 },
    { "msgget", 6 },
    { "msgrcv", 6 },
    { "msgsnd", 6 },
    { "printf", 6 },
    { "rename", 6 },
    { "return", 6 },
    { "rindex", 6 },
    { "scalar", 6 },
    { "select", 6 },
    { "semctl", 6 },
    { "semget", 6 },
    { "shmctl", 6 },
    { "shmget", 6 },
    { "socket", 6 },
    { "splice", 6 },
    { "substr", 6 },
    { "system", 6 },
    { "unless", 6 },
    { "values", 6 },
    { "binmode", 7 },
    { "connect", 7 },
    { "dbmopen", 7 },
    { "defined", 7 },
    { "foreach", 7 },
    { "lcfirst", 7 },
    { "opendir", 7 },
    { "package", 7 },
    { "readdir", 7 },
    { "require", 7 },
    { "reverse", 7 },
    { "seekdir", 7 },
    { "shmread", 7 },
    { "sprintf", 7 },
    { "symlink", 7 },
    { "sysopen", 7 },
    { "sysread", 7 },
    { "sysseek", 7 },
    { "telldir", 7 },
    { "ucfirst", 7 },
    { "unshift", 7 },
    { "waitpid", 7 },
    { "closedir", 8 },
    { "continue", 8 },
    { "dbmclose", 8 },
    { "endgrent", 8 },
    { "endpwent", 8 },
    { "readline", 8 },
    { "readlink", 8 },
    { "readpipe", 8 },
    { "setgrent", 8 },
    { "setpwent", 8 },
    { "shmwrite", 8 },
    { "shutdown", 8 },
    { "syswrite", 8 },
    { "truncate", 8 },
    { "endnetent", 9 },
    { "localtime", 9 },
    { "prototype", 9 },
    { "quotemeta", 9 },
    { "rewinddir", 9 },
    { "setnetent", 9 },
    { "wantarray", 9 },
    { "endhostent", 10 },
    { "endservent", 10 },
    { "sethostent", 10 },
    { "setservent", 10 },
    { "setsockopt", 10 },
    { "socketpair", 10 },
    { "endprotoent", 11 },
    { "setprotoent", 11 },
};

static SlopKwEntry sql_keywords[] = {
    { "as", 2 },
    { "by", 2 },
    { "if", 2 },
    { "in", 2 },
    { "is", 2 },
    { "of", 2 },
    { "on", 2 },
    { "or", 2 },
    { "to", 2 },
    { "add", 3 },
    { "all", 3 },
    { "and", 3 },
    { "any", 3 },
    { "asc", 3 },
    { "end", 3 },
    { "for", 3 },
    { "key", 3 },
    { "not", 3 },
    { "off", 3 },
    { "set", 3 },
    { "top", 3 },
    { "use", 3 },
    { "bulk", 4 },
    { "case", 4 },
    { "dbcc", 4 },
    { "deny", 4 },
    { "desc", 4 },
    { "disk", 4 },
    { "drop", 4 },
    { "dump", 4 },
    { "else", 4 },
    { "exec", 4 },
    { "exit", 4 },
    { "file", 4 },
    { "from", 4 },
    { "full", 4 },
    { "goto", 4 },
    { "into", 4 },
    { "join", 4 },
    { "kill", 4 },
    { "left", 4 },
    { "like", 4 },
    { "load", 4 },
    { "null", 4 },
    { "open", 4 },
    { "over", 4 },
    { "plan", 4 },
    { "proc", 4 },
    { "read", 4 },
    { "rule", 4 },
    { "save", 4 },
    { "some", 4 },
    { "then", 4 },
    { "tran", 4 },
    { "user", 4 },
    { "view", 4 },
    { "when", 4 },
    { "with", 4 },
    { "alter", 5 },
    { "begin", 5 },
    { "break", 5 },
    { "check", 5 },
    { "close", 5 },
    { "cross", 5 },
    { "fetch", 5 },
    { "grant", 5 },
    { "group", 5 },
    { "index", 5 },
    { "inner", 5 },
    { "merge", 5 },
    { "order", 5 },
    { "outer", 5 },
    { "pivot", 5 },
    { "print", 5 },
    { "right", 5 },
    { "table", 5 },
    { "union", 5 },
    { "where", 5 },
    { "while", 5 },
    { "backup", 6 },
    { "browse", 6 },
    { "column", 6 },
    { "commit", 6 },
    { "create", 6 },
    { "cursor", 6 },
    { "delete", 6 },
    { "double", 6 },
    { "errlvl", 6 },
    { "escape", 6 },
    { "except", 6 },
    { "exists", 6 },
    { "having", 6 },
    { "insert", 6 },
    { "lineno", 6 },
    { "nullif", 6 },
    { "option", 6 },
    { "public", 6 },
    { "return", 6 },
    { "revert", 6 },
    { "revoke", 6 },
    { "schema", 6 },
    { "select", 6 },
    { "unique", 6 },
    { "update", 6 },
    { "values", 6 },
    { "between", 7 },
    { "cascade", 7 },
    { "collate", 7 },
    { "compute", 7 },
    { "connect", 7 },
    { "convert", 7 },
    { "current", 7 },
    { "declare", 7 },
    { "default", 7 },
    { "execute", 7 },
    { "foreign", 7 },
    { "nocheck", 7 },
    { "offsets", 7 },
    { "openxml", 7 },
    { "percent", 7 },
    { "primary", 7 },
    { "restore", 7 },
    { "setuser", 7 },
    { "trigger", 7 },
    { "tsequal", 7 },
    { "unpivot", 7 },
    { "varying", 7 },
    { "waitfor", 7 },
    { "coalesce", 8 },
    { "contains", 8 },
    { "continue", 8 },
    { "database", 8 },
    { "distinct", 8 },
    { "external", 8 },
    { "freetext", 8 },
    { "function", 8 },
    { "holdlock", 8 },
    { "identity", 8 },
    { "national", 8 },
    { "readtext", 8 },
    { "restrict", 8 },
    { "rollback", 8 },
    { "rowcount", 8 },
    { "shutdown", 8 },
    { "textsize", 8 },
    { "truncate", 8 },
    { "clustered", 9 },
    { "intersect", 9 },
    { "openquery", 9 },
    { "precision", 9 },
    { "procedure", 9 },
    { "raiserror", 9 },
    { "writetext", 9 },
    { "checkpoint", 10 },
    { "constraint", 10 },
    { "deallocate", 10 },
    { "fillfactor", 10 },
    { "openrowset", 10 },
    { "references", 10 },
    { "rowguidcol", 10 },
    { "statistics", 10 },
    { "updatetext", 10 },
    { "distributed", 11 },
    { "identitycol", 11 },
    { "reconfigure", 11 },
    { "replication", 11 },
    { "system_user", 11 },
    { "tablesample", 11 },
    { "transaction", 11 },
    { "try_convert", 11 },
    { "current_date", 12 },
    { "current_time", 12 },
    { "current_user", 12 },
    { "nonclustered", 12 },
    { "session_user", 12 },
    { "authorization", 13 },
    { "containstable", 13 },
    { "freetexttable", 13 },
    { "securityaudit", 13 },
    { "opendatasource", 14 },
    { "identity_insert", 15 },
    { "current_timestamp", 17 },
    { "semantickeyphrasetable", 22 },
    { "semanticsimilaritytable", 23 },
    { "semanticsimilaritydetailstable", 30 },
};

static SlopKwEntry swift_keywords[] = {
    { "as", 2 },
    { "do", 2 },
    { "if", 2 },
    { "in", 2 },
    { "is", 2 },
    { "Any", 3 },
    { "for", 3 },
    { "let", 3 },
    { "nil", 3 },
    { "try", 3 },
    { "var", 3 },
    { "case", 4 },
    { "else", 4 },
    { "enum", 4 },
    { "func", 4 },
    { "init", 4 },
    { "open", 4 },
    { "self", 4 },
    { "Self", 4 },
    { "true", 4 },
    { "break", 5 },
    { "catch", 5 },
    { "class", 5 },
    { "defer", 5 },
    { "false", 5 },
    { "guard", 5 },
    { "inout", 5 },
    { "super", 5 },
    { "throw", 5 },
    { "where", 5 },
    { "while", 5 },
    { "deinit", 6 },
    { "import", 6 },
    { "public", 6 },
    { "repeat", 6 },
    { "return", 6 },
    { "static", 6 },
    { "struct", 6 },
    { "switch", 6 },
    { "throws", 6 },
    { "default", 7 },
    { "private", 7 },
    { "continue", 8 },
    { "escaping", 8 },
    { "internal", 8 },
    { "operator", 8 },
    { "protocol", 8 },
    { "rethrows", 8 },
    { "available", 9 },
    { "extension", 9 },
    { "subscript", 9 },
    { "typealias", 9 },
    { "autoclosur", 10 },
    { "fallthrough", 11 },
    { "fileprivate", 11 },
    { "associatedtype", 14 },
    { "precedencegroup", 15 },
    { "discardableResult", 17 },
};

static SlopKwEntry kotlin_keywords[] = {
    { "as", 2 },
    { "by", 2 },
    { "do", 2 },
    { "if", 2 },
    { "in", 2 },
    { "is", 2 },
    { "it", 2 },
    { "!in", 3 },
    { "!is", 3 },
    { "as?", 3 },
    { "for", 3 },
    { "fun", 3 },
    { "get", 3 },
    { "out", 3 },
    { "set", 3 },
    { "try", 3 },
    { "val", 3 },
    { "var", 3 },
    { "data", 4 },
    { "else", 4 },
    { "enum", 4 },
    { "file", 4 },
    { "init", 4 },
    { "null", 4 },
    { "open", 4 },
    { "this", 4 },
    { "true", 4 },
    { "when", 4 },
    { "break", 5 },
    { "catch", 5 },
    { "class", 5 },
    { "const", 5 },
    { "false", 5 },
    { "field", 5 },
    { "final", 5 },
    { "infix", 5 },
    { "inner", 5 },
    { "param", 5 },
    { "super", 5 },
    { "throw", 5 },
    { "value", 5 },
    { "where", 5 },
    { "while", 5 },
    { "actual", 6 },
    { "expect", 6 },
    { "import", 6 },
    { "inline", 6 },
    { "object", 6 },
    { "public", 6 },
    { "return", 6 },
    { "sealed", 6 },
    { "typeof", 6 },
    { "vararg", 6 },
    { "dynamic", 7 },
    { "finally", 7 },
    { "package", 7 },
    { "private", 7 },
    { "reified", 7 },
    { "suspend", 7 },
    { "tailrec", 7 },
    { "abstract", 8 },
    { "continue", 8 },
    { "delegate", 8 },
    { "external", 8 },
    { "internal", 8 },
    { "lateinit", 8 },
    { "noinline", 8 },
    { "operator", 8 },
    { "override", 8 },
    { "property", 8 },
    { "receiver", 8 },
    { "setparam", 8 },
    { "companion", 9 },
    { "interface", 9 },
    { "protected", 9 },
    { "typealias", 9 },
    { "annotation", 10 },
    { "constructor", 11 },
    { "crossinline", 11 },
};

static SlopKwEntry csharp_keywords[] = {
    { "as", 2 },
    { "by", 2 },
    { "do", 2 },
    { "if", 2 },
    { "in", 2 },
    { "is", 2 },
    { "on", 2 },
    { "add", 3 },
    { "for", 3 },
    { "get", 3 },
    { "int", 3 },
    { "let", 3 },
    { "new", 3 },
    { "out", 3 },
    { "ref", 3 },
    { "set", 3 },
    { "try", 3 },
    { "var", 3 },
    { "base", 4 },
    { "bool", 4 },
    { "byte", 4 },
    { "case", 4 },
    { "char", 4 },
    { "else", 4 },
    { "enum", 4 },
    { "from", 4 },
    { "goto", 4 },
    { "into", 4 },
    { "join", 4 },
    { "lock", 4 },
    { "long", 4 },
    { "null", 4 },
    { "this", 4 },
    { "true", 4 },
    { "uint", 4 },
    { "void", 4 },
    { "when", 4 },
    { "alias", 5 },
    { "async", 5 },
    { "await", 5 },
    { "break", 5 },
    { "catch", 5 },
    { "class", 5 },
    { "const", 5 },
    { "event", 5 },
    { "false", 5 },
    { "fixed", 5 },
    { "float", 5 },
    { "group", 5 },
    { "sbyte", 5 },
    { "short", 5 },
    { "throw", 5 },
    { "ulong", 5 },
    { "using", 5 },
    { "value", 5 },
    { "where", 5 },
    { "while", 5 },
    { "yield", 5 },
    { "double", 6 },
    { "equals", 6 },
    { "extern", 6 },
    { "global", 6 },
    { "nameof", 6 },
    { "object", 6 },
    { "params", 6 },
    { "public", 6 },
    { "remove", 6 },
    { "return", 6 },
    { "sealed", 6 },
    { "select", 6 },
    { "sizeof", 6 },
    { "static", 6 },
    { "string", 6 },
    { "struct", 6 },
    { "switch", 6 },
    { "typeof", 6 },
    { "unsafe", 6 },
    { "ushort", 6 },
    { "checked", 7 },
    { "decimal", 7 },
    { "default", 7 },
    { "dynamic", 7 },
    { "finally", 7 },
    { "foreach", 7 },
    { "orderby", 7 },
    { "partial", 7 },
    { "private", 7 },
    { "virtual", 7 },
    { "abstract", 8 },
    { "continue", 8 },
    { "delegate", 8 },
    { "explicit", 8 },
    { "implicit", 8 },
    { "internal", 8 },
    { "operator", 8 },
    { "override", 8 },
    { "readonly", 8 },
    { "volatile", 8 },
    { "ascending", 9 },
    { "interface", 9 },
    { "namespace", 9 },
    { "protected", 9 },
    { "unchecked", 9 },
    { "descending", 10 },
    { "stackalloc", 10 },
};



static SlopKwEntry css_keywords[] = {
    { "-o-", 3 },
    { "-ms-", 4 },
    { "-moz-", 5 },
    { "@page", 5 },
    { "@media", 6 },
    { "@import", 7 },
    { "-webkit-", 8 },
    { "@charset", 8 },
    { "property", 8 },
    { "@document", 9 },
    { "@supports", 9 },
    { "@viewport", 9 },
    { "@font-face", 10 },
    { "@keyframes", 10 },
    { "@namespace", 10 },
    { "color-adjust", 12 },
    { "@counter-style", 14 },
};

static SlopKwEntry json_keywords[] = {
    { "null", 4 },
    { "true", 4 },
    { "false", 5 },
};




static SlopKwEntry dockerfile_keywords[] = {
    { "AS", 2 },
    { "ADD", 3 },
    { "ARG", 3 },
    { "CMD", 3 },
    { "ENV", 3 },
    { "RUN", 3 },
    { "COPY", 4 },
    { "FROM", 4 },
    { "USER", 4 },
    { "LABEL", 5 },
    { "SHELL", 5 },
    { "EXPOSE", 6 },
    { "VOLUME", 6 },
    { "ONBUILD", 7 },
    { "WORKDIR", 7 },
    { "ENTRYPOINT", 10 },
    { "MAINTAINER", 10 },
    { "STOPSIGNAL", 10 },
    { "HEALTHCHECK", 11 },
};

static SlopKwEntry makefile_keywords[] = {
    { "else", 4 },
    { "ifeq", 4 },
    { "endef", 5 },
    { "endif", 5 },
    { "ifneq", 5 },
    { "vpath", 5 },
    { ".PHONY", 6 },
    { ".POSIX", 6 },
    { "define", 6 },
    { "export", 6 },
    { ".IGNORE", 7 },
    { ".SILENT", 7 },
    { "include", 7 },
    { "private", 7 },
    { ".DEFAULT", 8 },
    { "override", 8 },
    { ".ONESHELL", 9 },
    { ".PRECIOUS", 9 },
    { ".SUFFIXES", 9 },
    { ".SECONDARY", 10 },
    { ".NOTPARALLEL", 12 },
    { ".INTERMEDIATE", 13 },
    { ".DELETE_ON_ERROR", 16 },
    { ".SECONDEXPANSION", 16 },
    { ".LOW_RESOLUTION_TIME", 20 },
    { ".EXPORT_ALL_VARIABLES", 21 },
};


static SlopKwEntry haskell_keywords[] = {
    { "_", 1 },
    { "as", 2 },
    { "do", 2 },
    { "if", 2 },
    { "in", 2 },
    { "of", 2 },
    { "let", 3 },
    { "mdo", 3 },
    { "rec", 3 },
    { "case", 4 },
    { "data", 4 },
    { "else", 4 },
    { "proc", 4 },
    { "then", 4 },
    { "type", 4 },
    { "class", 5 },
    { "infix", 5 },
    { "where", 5 },
    { "forall", 6 },
    { "hiding", 6 },
    { "import", 6 },
    { "infixl", 6 },
    { "infixr", 6 },
    { "module", 6 },
    { "default", 7 },
    { "foreign", 7 },
    { "newtype", 7 },
    { "deriving", 8 },
    { "instance", 8 },
    { "qualified", 9 },
};

static SlopKwEntry erlang_keywords[] = {
    { "if", 2 },
    { "of", 2 },
    { "or", 2 },
    { "and", 3 },
    { "bor", 3 },
    { "bsl", 3 },
    { "bsr", 3 },
    { "div", 3 },
    { "end", 3 },
    { "fun", 3 },
    { "let", 3 },
    { "not", 3 },
    { "rem", 3 },
    { "try", 3 },
    { "xor", 3 },
    { "band", 4 },
    { "bnot", 4 },
    { "bxor", 4 },
    { "case", 4 },
    { "cond", 4 },
    { "when", 4 },
    { "after", 5 },
    { "begin", 5 },
    { "catch", 5 },
    { "orelse", 6 },
    { "andalso", 7 },
    { "receive", 7 },
};



static SlopLangProfile slop_profiles[LANG_COUNT] = {
    [LANG_NONE] = { NULL, NULL, NULL, NULL, 0, NULL, 0, NULL, 0 },
    [LANG_C] = { "//", "/*", "*/", "\"'", 1, c_keywords, 69, c_types, 24 },
    [LANG_CPP] = { "//", "/*", "*/", "\"'", 1, cpp_keywords, 86, cpp_types, 27 },
    [LANG_RUST] = { "//", "/*", "*/", "\"'", 1, rust_keywords, 40, rust_types, 24 },
    [LANG_GO] = { "//", "/*", "*/", "\"'", 1, go_keywords, 25, go_types, 20 },
    [LANG_JAVASCRIPT] = { "//", "/*", "*/", "\"'", 1, javascript_keywords, 42, NULL, 0 },
    [LANG_TYPESCRIPT] = { "//", "/*", "*/", "\"'", 1, typescript_keywords, 63, NULL, 0 },
    [LANG_JAVA] = { "//", "/*", "*/", "\"'", 1, java_keywords, 53, NULL, 0 },
    [LANG_PYTHON] = { "#", NULL, NULL, "\"'", 0, python_keywords, 36, NULL, 0 },
    [LANG_SHELL] = { "#", NULL, NULL, "\"'", 0, shell_keywords, 33, NULL, 0 },
    [LANG_RUBY] = { "#", NULL, NULL, "\"'", 0, ruby_keywords, 36, NULL, 0 },
    [LANG_PHP] = { "//", "/*", "*/", "\"'", 1, php_keywords, 73, NULL, 0 },
    [LANG_LUA] = { ";", NULL, NULL, "\"'", 0, lua_keywords, 22, NULL, 0 },
    [LANG_PERL] = { "#", NULL, NULL, "\"'", 0, perl_keywords, 190, NULL, 0 },
    [LANG_SQL] = { "--", "/*", "*/", "'\"", 0, sql_keywords, 185, NULL, 0 },
    [LANG_SWIFT] = { "//", "/*", "*/", "\"'", 1, swift_keywords, 58, NULL, 0 },
    [LANG_KOTLIN] = { "//", "/*", "*/", "\"'", 1, kotlin_keywords, 79, NULL, 0 },
    [LANG_CSHARP] = { "//", "/*", "*/", "\"'", 1, csharp_keywords, 105, NULL, 0 },
    [LANG_HTML] = { NULL, "<!--", "-->", "\"'", 0, NULL, 0, NULL, 0 },
    [LANG_XML] = { NULL, "<!--", "-->", "\"'", 0, NULL, 0, NULL, 0 },
    [LANG_CSS] = { NULL, "/*", "*/", "\"'", 0, css_keywords, 17, NULL, 0 },
    [LANG_JSON] = { NULL, NULL, NULL, "\"", 0, json_keywords, 3, NULL, 0 },
    [LANG_YAML] = { "#", NULL, NULL, "\"'", 0, NULL, 0, NULL, 0 },
    [LANG_TOML] = { "#", NULL, NULL, "\"'", 0, NULL, 0, NULL, 0 },
    [LANG_INI] = { "#;", NULL, NULL, "\"'", 0, NULL, 0, NULL, 0 },
    [LANG_DOCKERFILE] = { "#", NULL, NULL, "\"'", 0, dockerfile_keywords, 19, NULL, 0 },
    [LANG_MAKEFILE] = { "#", NULL, NULL, "\"'", 0, makefile_keywords, 26, NULL, 0 },
    [LANG_LISP] = { ";", "#|", "|#", "\"", 0, NULL, 0, NULL, 0 },
    [LANG_HASKELL] = { "--", "{-", "-}", "\"'", 0, haskell_keywords, 30, NULL, 0 },
    [LANG_ERLANG] = { "%", NULL, NULL, "\"'", 0, erlang_keywords, 27, NULL, 0 },
    [LANG_MARKDOWN] = { NULL, NULL, NULL, "\"'`", 0, NULL, 0, NULL, 0 },
    [LANG_ASSEMBLY] = { ";", NULL, NULL, "'\"", 0, NULL, 0, NULL, 0 },
};

static struct { const char* ext; int lang; } slop_ext_map[] = {
    { ".properties", LANG_INI },
    { ".dockerfile", LANG_DOCKERFILE },
    { "GNUmakefile", LANG_MAKEFILE },
    { "Dockerfile", LANG_DOCKERFILE },
    { ".markdown", LANG_MARKDOWN },
    { ".gemspec", LANG_RUBY },
    { "Makefile", LANG_MAKEFILE },
    { "makefile", LANG_MAKEFILE },
    { ".phtml", LANG_PHP },
    { ".swift", LANG_SWIFT },
    { ".xhtml", LANG_HTML },
    { ".mdown", LANG_MARKDOWN },
    { ".slop", LANG_C },
    { ".java", LANG_JAVA },
    { ".bash", LANG_SHELL },
    { ".fish", LANG_SHELL },
    { ".rake", LANG_RUBY },
    { ".html", LANG_HTML },
    { ".scss", LANG_CSS },
    { ".sass", LANG_CSS },
    { ".less", LANG_CSS },
    { ".json", LANG_JSON },
    { ".yaml", LANG_YAML },
    { ".toml", LANG_TOML },
    { ".conf", LANG_INI },
    { ".lisp", LANG_LISP },
    { ".cljs", LANG_LISP },
    { ".cljc", LANG_LISP },
    { ".nasm", LANG_ASSEMBLY },
    { ".cpp", LANG_CPP },
    { ".cxx", LANG_CPP },
    { ".hpp", LANG_CPP },
    { ".hxx", LANG_CPP },
    { ".mjs", LANG_JAVASCRIPT },
    { ".cjs", LANG_JAVASCRIPT },
    { ".tsx", LANG_TYPESCRIPT },
    { ".pyw", LANG_PYTHON },
    { ".pyi", LANG_PYTHON },
    { ".zsh", LANG_SHELL },
    { ".ksh", LANG_SHELL },
    { ".php", LANG_PHP },
    { ".lua", LANG_LUA },
    { ".sql", LANG_SQL },
    { ".kts", LANG_KOTLIN },
    { ".htm", LANG_HTML },
    { ".xml", LANG_XML },
    { ".svg", LANG_XML },
    { ".xsd", LANG_XML },
    { ".xsl", LANG_XML },
    { ".css", LANG_CSS },
    { ".yml", LANG_YAML },
    { ".ini", LANG_INI },
    { ".cfg", LANG_INI },
    { ".clj", LANG_LISP },
    { ".scm", LANG_LISP },
    { ".rkt", LANG_LISP },
    { ".lhs", LANG_HASKELL },
    { ".erl", LANG_ERLANG },
    { ".hrl", LANG_ERLANG },
    { ".asm", LANG_ASSEMBLY },
    { ".cc", LANG_CPP },
    { ".rs", LANG_RUST },
    { ".go", LANG_GO },
    { ".js", LANG_JAVASCRIPT },
    { ".ts", LANG_TYPESCRIPT },
    { ".py", LANG_PYTHON },
    { ".sh", LANG_SHELL },
    { ".rb", LANG_RUBY },
    { ".pl", LANG_PERL },
    { ".pm", LANG_PERL },
    { ".kt", LANG_KOTLIN },
    { ".cs", LANG_CSHARP },
    { ".mk", LANG_MAKEFILE },
    { ".ss", LANG_LISP },
    { ".hs", LANG_HASKELL },
    { ".md", LANG_MARKDOWN },
    { ".c", LANG_C },
    { ".h", LANG_C },
    { ".s", LANG_ASSEMBLY },
    { NULL, LANG_NONE }
};

static int slop_hl_word_char(char c) {
    return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_';
}

static int slop_hl_kw_cmp(const void* a, const void* b) {
    const SlopKwEntry* ka = (const SlopKwEntry*)a;
    const SlopKwEntry* kb = (const SlopKwEntry*)b;
    if (ka->len != kb->len) return ka->len - kb->len;
    return strcmp(ka->word, kb->word);
}

static int slop_hl_find_kw(const SlopKwEntry* table, int count, const char* w, int len) {
    if (!table || count <= 0) return 0;
    SlopKwEntry key = { w, len };
    return bsearch(&key, table, count, sizeof(SlopKwEntry), slop_hl_kw_cmp) != NULL;
}

static int slop_hl_startswith(const char* s, int slen, int pos, const char* prefix) {
    if (!prefix) return 0;
    int plen = (int)strlen(prefix);
    return pos + plen <= slen && memcmp(s + pos, prefix, plen) == 0;
}

static int slop_hl_find_quote(const char* quotes, char c) {
    if (!quotes) return 0;
    for (int i = 0; quotes[i]; i++) if (quotes[i] == c) return 1;
    return 0;
}

int slop_hl_detect_lang(SlopString filename) {
    if (filename.length == 0) return LANG_NONE;
    for (int i = 0; slop_ext_map[i].ext; i++) {
        const char* ext = slop_ext_map[i].ext;
        int elen = (int)strlen(ext);
        if ((int)filename.length >= elen && memcmp(filename.data + filename.length - elen, ext, elen) == 0) {
            return slop_ext_map[i].lang;
        }
    }
    // Check basename matches like Dockerfile, Makefile.
    const char* slash = strrchr(filename.data, '/');
    const char* name = slash ? slash + 1 : filename.data;
    for (int i = 0; slop_ext_map[i].ext; i++) {
        const char* ext = slop_ext_map[i].ext;
        if (ext[0] != '.') {
            if (strncmp(name, ext, strlen(ext)) == 0) return slop_ext_map[i].lang;
        }
    }
    return LANG_NONE;
}

void slop_hl_print(SlopString* line, int start, int len, int lang) {
    if (lang <= 0 || lang >= LANG_COUNT || len <= 0) {
        write(STDOUT_FILENO, line->data + start, len);
        return;
    }
    const SlopLangProfile* p = &slop_profiles[lang];
    int end = start + len;
    if (end > (int)line->length) end = (int)line->length;
    int i = start;
    while (i < end) {
        // Single-line comments
        if (p->single) {
            for (int k = 0; p->single[k]; k++) {
                if (line->data[i] == p->single[k]) {
                    write(STDOUT_FILENO, HL_COMMENT, strlen(HL_COMMENT));
                    write(STDOUT_FILENO, line->data + i, end - i);
                    write(STDOUT_FILENO, HL_RESET, strlen(HL_RESET));
                    return;
                }
            }
        }
        // Multi-line comments (single-line portion only)
        if (p->multi_start && slop_hl_startswith(line->data, end, i, p->multi_start)) {
            int mslen = (int)strlen(p->multi_start);
            int melen = p->multi_end ? (int)strlen(p->multi_end) : 0;
            int j = i + mslen;
            while (j < end) {
                if (melen && slop_hl_startswith(line->data, end, j, p->multi_end)) {
                    j += melen;
                    break;
                }
                j++;
            }
            write(STDOUT_FILENO, HL_COMMENT, strlen(HL_COMMENT));
            write(STDOUT_FILENO, line->data + i, j - i);
            write(STDOUT_FILENO, HL_RESET, strlen(HL_RESET));
            i = j;
            continue;
        }
        // Strings
        if (p->quotes && slop_hl_find_quote(p->quotes, line->data[i])) {
            char q = line->data[i];
            int j = i + 1;
            while (j < end && line->data[j] != q) {
                if (line->data[j] == '\\' && j + 1 < end) j += 2;
                else j++;
            }
            if (j < end) j++;
            write(STDOUT_FILENO, HL_STRING, strlen(HL_STRING));
            write(STDOUT_FILENO, line->data + i, j - i);
            write(STDOUT_FILENO, HL_RESET, strlen(HL_RESET));
            i = j;
            continue;
        }
        // Preprocessor directives (C-like, line start)
        if (p->has_preproc && i == start && line->data[i] == '#') {
            int j = i;
            while (j < end && line->data[j] != ' ' && line->data[j] != '\t') j++;
            write(STDOUT_FILENO, HL_PREPROC, strlen(HL_PREPROC));
            write(STDOUT_FILENO, line->data + i, j - i);
            write(STDOUT_FILENO, HL_RESET, strlen(HL_RESET));
            i = j;
            continue;
        }
        // Numbers
        if ((line->data[i] >= '0' && line->data[i] <= '9') ||
            (line->data[i] == '.' && i + 1 < end && line->data[i+1] >= '0' && line->data[i+1] <= '9')) {
            int j = i;
            while (j < end && ((line->data[j] >= '0' && line->data[j] <= '9') || line->data[j] == '.' ||
                   line->data[j] == 'x' || line->data[j] == 'X' ||
                   (line->data[j] >= 'a' && line->data[j] <= 'f') ||
                   (line->data[j] >= 'A' && line->data[j] <= 'F'))) j++;
            write(STDOUT_FILENO, HL_NUMBER, strlen(HL_NUMBER));
            write(STDOUT_FILENO, line->data + i, j - i);
            write(STDOUT_FILENO, HL_RESET, strlen(HL_RESET));
            i = j;
            continue;
        }
        // Words
        if (slop_hl_word_char(line->data[i])) {
            int j = i;
            while (j < end && slop_hl_word_char(line->data[j])) j++;
            int wlen = j - i;
            if (slop_hl_find_kw(p->keywords, p->kw_count, line->data + i, wlen)) {
                write(STDOUT_FILENO, HL_KEYWORD, strlen(HL_KEYWORD));
                write(STDOUT_FILENO, line->data + i, wlen);
                write(STDOUT_FILENO, HL_RESET, strlen(HL_RESET));
            } else if (slop_hl_find_kw(p->types, p->type_count, line->data + i, wlen)) {
                write(STDOUT_FILENO, HL_TYPE, strlen(HL_TYPE));
                write(STDOUT_FILENO, line->data + i, wlen);
                write(STDOUT_FILENO, HL_RESET, strlen(HL_RESET));
            } else {
                write(STDOUT_FILENO, line->data + i, wlen);
            }
            i = j;
            continue;
        }
        write(STDOUT_FILENO, line->data + i, 1);
        i++;
    }
}

SlopHlDiag slop_hl_diagnostics(SlopArray lines, int lang) {
    SlopHlDiag diag = {0, 0};
    if (lang <= 0 || lang >= LANG_COUNT) return diag;
    const SlopLangProfile* p = &slop_profiles[lang];
    int paren = 0, bracket = 0, brace = 0;
    int in_ml = 0; // 1 = inside multi-line comment (across lines)
    int in_string = 0;
    char string_quote = 0;

    for (int row = 0; row < (int)lines.length; row++) {
        SlopString* line = (SlopString*)slop_array_get(lines, row);
        int len = (int)line->length;
        int trailing_ws = 0;
        for (int i = len - 1; i >= 0; i--) {
            if (line->data[i] == ' ' || line->data[i] == '\t') trailing_ws++;
            else break;
        }
        if (trailing_ws > 0) diag.warnings++;

        for (int i = 0; i < len; ) {
            if (in_ml) {
                if (p->multi_end && slop_hl_startswith(line->data, len, i, p->multi_end)) {
                    i += (int)strlen(p->multi_end);
                    in_ml = 0;
                } else {
                    i++;
                }
                continue;
            }
            // Single-line comment
            if (p->single) {
                int in_single = 0;
                for (int k = 0; p->single[k]; k++) {
                    if (line->data[i] == p->single[k]) { in_single = 1; break; }
                }
                if (in_single) break;
            }
            // Multi-line comment start
            if (p->multi_start && slop_hl_startswith(line->data, len, i, p->multi_start)) {
                i += (int)strlen(p->multi_start);
                in_ml = 1;
                continue;
            }
            // String handling
            if (!in_string && p->quotes && slop_hl_find_quote(p->quotes, line->data[i])) {
                in_string = 1;
                string_quote = line->data[i];
                i++;
                continue;
            }
            if (in_string) {
                if (line->data[i] == '\\' && i + 1 < len) { i += 2; continue; }
                if (line->data[i] == string_quote) { in_string = 0; }
                i++;
                continue;
            }
            // Bracket counting
            if (line->data[i] == '(') paren++;
            else if (line->data[i] == ')') paren--;
            else if (line->data[i] == '[') bracket++;
            else if (line->data[i] == ']') bracket--;
            else if (line->data[i] == '{') brace++;
            else if (line->data[i] == '}') brace--;
            i++;
        }
    }

    diag.errors += (paren < 0 ? -paren : paren);
    diag.errors += (bracket < 0 ? -bracket : bracket);
    diag.errors += (brace < 0 ? -brace : brace);
    if (in_string) diag.errors++;
    if (in_ml) diag.errors++;
    return diag;
}
